version: "3"

services:
  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  # app:
  #   build: .
  #   container_name: evento-service
  #   restart: always
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   depends_on:
  #     - postgres
  #   ports:
  #     - ${PORT}:${PORT}
  #   command: >
  #     sh -c "pm2-runtime index.js"
