# services:
#   - docker

# before_install:
#   - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in id_rsa.enc -out id_rsa -d
# addons:
#   ssh_known_hosts: ec2-54-243-145-38.compute-1.amazonaws.com
# script:
#   - docker-machine ssh manager01 bash startup.sh
before_install:
  - |
    echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
    if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.md$)|(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)|^(docs)/'
    then
      echo "Only doc files were updated, not running the CI."
      exit
    fi
script:
  - echo ${TRAVIS_COMMIT_RANGE}
