env:
  matrix:
    secure: dN9d74XzU/DPD6EfqNK8P8mFMGkhePEhXemEDIcT+YTp6+vzvUrVev8lsXNWgICn3dIoTSG/reJaO5VL/iDPTTt9cI3uCLTHRPG6v3dIOygCHrlVzRlOB9TsSWFv5IvxDaeByHBWYbKv1+4qH3gep2B24N8I+24NqpmzNATAW2b3UweefbH+K7laMiPy5dvppUU4oLSBY4h1Qnd/L0Xeed1iqfJHVYlXPQO0UXvDLTwrW+KzkfLqSGvCXeKNoWvBx5KuphlSiGXW59Kf7sd76eQP91mswsEqtnfikgImq0LKUPFREHYFlPtcvseMhAGRuJ/oCs9OeHSsE1wQbZ/AGfY6J8nTYtOa+TXR+AEGNLsch27yWIpDvsJ3M8XSlM6NvP5nglMqjT0VhRma5Y8Od67YDJvZU+ASm5l8NHOFjNrfbYQ25hQJ5J50bT1nCdL9zro9SFbt9/wjhId+71zwCe5hDxZxDZLS2SubtXJTepXMAfl5fUrPnhIawEdjPrV/EbG028H5HxGQktiGXc+jBdqSztWkQ9T6fnEt+6poeKGvrjfBZ2jRjPs9u0Hm0R8X0tfOa4XGfOZ6JiBmcR9prJRhUxqvfd1ajEoTM4aADXvRH4I7hWvKmU8sFTdYUdSGXF/27rJ32cRZ6WoH3E1yRuspLS8iEDIHG3BGNQIcZKY=

before_script:
  - git config --global user.email "g_bernardo10@hotmail.com"
  - git config --global user.name "GBernardo10"

script:
  - bash ./script.sh -prod
  #- openssl aes-256-cbc -k "$travis_key_password" -d -md sha256 -a -in travis_key.enc -out travis_key
