# services:
#   - docker

# before_install:
#   - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in id_rsa.enc -out id_rsa -d
# addons:
#   ssh_known_hosts: ec2-54-243-145-38.compute-1.amazonaws.com
# script:
#   - docker-machine ssh manager01 bash startup.sh
