version: "3"

services:
  postgres:
    image: postgres:11
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  app:
    # image: node:12.16.1-alpine
    build: .
    container_name: user-service
    restart: always
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
