version: "3"

services:
  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  app:
    build: .
    container_name: evento-service
    restart: always
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
